name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Cache buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          buildozer-${{ runner.os }}-

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-dev libffi-dev libssl-dev git unzip default-jdk \
          automake libtool autoconf pkg-config build-essential \
          zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev \
          libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev \
          autotools-dev autoconf-archive m4

    - name: Fix autoconf toolchain
      run: |
        # Regenerate autotools configuration
        sudo autoupdate --version || echo "autoupdate not available"
        # Ensure latest libtool macros are available
        sudo aclocal --install -I /usr/share/aclocal || echo "aclocal setup done"
        # Fix potential macro issues
        export ACLOCAL_PATH="/usr/share/aclocal:$ACLOCAL_PATH"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install buildozer cython==0.29.33
        # Install only Android-compatible dependencies
        pip install kivy plyer requests

    - name: Validate project structure
      run: |
        if [ ! -f buildozer.spec ]; then
          echo "buildozer.spec not found, initializing..."
          buildozer init
        fi
        echo "✅ buildozer.spec found"
        echo "Project structure:"
        ls -la

    - name: Build Android APK
      run: |
        mkdir -p ~/.android
        echo "Starting Android build..."
        echo "Buildozer version:"
        buildozer version
        echo "Available commands:"
        buildozer --help
        echo "Building APK..."
        buildozer android debug --verbose
      env:
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        ANDROID_HOME: /usr/local/lib/android/sdk

    - name: List build artifacts
      run: |
        find . -name "*.apk" -type f
        ls -la bin/ || echo "No bin directory found"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: focusapp-debug-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/outputs/apk/debug/*.apk
        if-no-files-found: warn

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/build-*/
          .buildozer/*.log
