name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install system dependencies (with libtool/autoconf fix)
      run: |
        sudo apt update
        sudo apt install -y \
          python3-dev libffi-dev libssl-dev git unzip default-jdk \
          automake libtool autoconf pkg-config

        # Prepare autoconf macros to avoid LT_SYS_SYMBOL_USCORE error
        libtoolize --force --copy
        aclocal
        autoconf

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Build Android APK
      run: |
        mkdir -p ~/.android
        echo "y" | buildozer android debug
      env:
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        ANDROID_HOME: /usr/local/lib/android/sdk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: focusapp-debug-apk
        path: bin/*.apk

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: .buildozer/android/platform/build-*/
